# Generated by Django 3.2 on 2021-06-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
    ]
