# Generated by Django 3.2 on 2021-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
